# Generated by Django 3.2.4 on 2024-02-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterwisePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255, null=True)),
                ('chapter_pdf_file', models.FileField(upload_to='pdfs/')),
                ('chapterP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
            ],
        ),
    ]
