# Generated by Django 3.2.4 on 2024-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_chapterwisepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stform',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
